### ISSUE TITLE
WADL is not deployed ***SR 3-26108882831***

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#7]
**Describe the bug**
From: Rigo, Linda M <Linda.M.Rigo@snapon.com> 
Sent: 27 May 2021 17:04
To: Jori, Amit <Amit.Jori@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>
Cc: Griffin, Tina <Tina.Griffin@snapon.com>; Hamilton, Mark W <Mark.W.Hamilton@snapon.com>; Liu, Sherry X <Sherry.X.Liu@snapon.com>
Subject: 12.2.10 Upgrade Issue

Hi Amit and Somu
I have found the following WADL is not deployed

Rest Service not deployed

**Responsibility Name**
Responsibility:

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/84878630/120422809-b8b95e00-c32e-11eb-94bb-b19899728988.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lindamrigo** [comment]
This is still not working. 
![SBS_CPQ_QUOTE_PKG](https://user-images.githubusercontent.com/85238444/120499255-e84b8300-c38d-11eb-904d-a47725ef7108.JPG)

**Comment by suhas-deshpande** [comment]
@SomuSundaramM : Can you please try to deploy standard package - ASO_QUOTE_PUB. As we checked earlier, it seems to have 2 duplicate procedures. If you still get any error with that, please raise SR with Oracle as we can see that these 2 packages (custom and standard) are valid in Oracle DB.

**Comment by vinaytalasila** [comment]
@amitjori : As per our today's status call could you please check whether this can be fixed by deleting from SOA and deploy it again or undeploy and deploy it again.

**Comment by lindamrigo** [comment]
The issues is the same

***@***.***D75B9D.41DA2F10]

**Comment by TinaGriffin** [comment]
I'm not sure if this will help....but I found the old SR where we had SOA issues before.  It may help for reference.  It was SR 3-17957049521 : SOA Deployment issues after refresh

**Comment by vinaytalasila** [comment]
Tina,

Thank you for sharing the information. @amitjori will look into that SR and we may have an update on this during our tomorrow's status meeting.

Thanks
Vinay Talasila

**Comment by amitjori** [comment]
Hello Tina,

I am not able to locate this SR 3-17957049521 : SOA Deployment issues after refresh. Is it possible for you to send me the extract of this SR in email?

Regards,
Amit

**Comment by TinaGriffin** [comment]
Attached is the old SR we had opened for SOA.

**Comment by TinaGriffin** [comment]
Attached is the old SR we had opened for SOA. SR 3-17957049521
[SR 3-17957049521.pdf](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6624529/SR.3-17957049521.pdf)

**Comment by TinaGriffin** [comment]
I found this within "12.2 E-Business Suite Integrated SOA Gateway Troubleshooting For REST, Java Web Service Invocation, And Other ISG Related Exceptions (Doc ID 2177901.1)".  It sounds pretty close to our error.  Can we try this?  
----------------------------------------

3. Issue 

Java Web Service Generation is failing

Error in Service Generation oracle.apps.fnd.isg.common.error.ISGException: Error in Service Generation at oracle.apps.fnd.isg.app.ebs.designer.pojo.POJOServiceDesigner.generateArtifacts(POJOServiceDesigner.java:396)

Steps to debug

Generally reimporting the ildt for the java webservice resolves the issue

     Generate the ildt file for the attached Java file once again with a new version
     Upload the ildt using FNDLOAD.
     Ensure the Interface definition is successfully loaded into Integration Repository.
     Log into Applications, and search for the custom service.
     Click on the "Rest Web Service" Tab.
     The custom webservice will not error
-------------------------------------------------------

**Comment by lindamrigo** [comment]
SBS_CPQ_QUOTE_PKG is not listed in SOA Integration Repository

**Comment by TinaGriffin** [comment]
Amit, I have found the instructions we used to deploy for the backend of the Quote pkg.  I'm uploading the zip file and a text file that were all included together in a folder I had.  Also I had a note that the non prod RFC # Non Prod RFC is : 3-7JOWDRQ.
[SBS_EBS_CPQ_HTMLQuote_Integration.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6677892/SBS_EBS_CPQ_HTMLQuote_Integration.txt)
[SBS_EBS_CPQ_HTMLQuote_Integration.zip](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6677894/SBS_EBS_CPQ_HTMLQuote_Integration.zip)

**Comment by TinaGriffin** [comment]
I've also found this ..it looks like the installation to create a new ildt file is in the .sh file.  In the example I'm displaying here it was for the Snapshot. sh file, but you could do the same with the Quote .sh file.  Replace the Snapshot .sh with the Quote .sh


-bash-3.2$ sh SBS_CPQ_SNAPSHOT_INST.sh
/dpqs2i/applmgr/CUSTOM/xbol/12.0.0/install

 Changing permissions for all files
 Moving files to their respective directories...
 Changing permissions for all files
Please enter password for apps:
Creating Package spec body for SBS_CPQ_SNAPSHOT_PKG


Creating ildt for the package
# Interface Repository Annotation Processor, 12.0.0

#
# Generating annotation output.
# Processing file 'SBS_CPQ_SNAPSHOT_PKG.pls'.
# Using YAPP-based parser.
#  Found a package-level annotation for 'SBS_CPQ_SNAPSHOT_PKG'.
#  Found a detail-level annotation...
# Found a procedure named 'GET_SNAPSHOTINFO'.
# Done all files.
File permission change to 777
SBS_CPQ_SNAPSHOT_INST.sh: line 167: -------------------------------------------------------------------------------------: command not found
Log filename : L6442804.log


Report filename : O6442804.out

installation Completed...
Please check installation log file : /dpqs2i/applmgr/CUSTOM/xbol/12.0.0/log/SBS_CPQ_SNAPSHOT_25_05_2018:10:10:11.log

-bash-3.2$

**Comment by SomuSundaramM** [comment]
Hi Tina/Team,

We were able to successfully deploy the SBS_CPQ_QUOTE_PKG in STG instance by Recreating ildt files. Attached the screenshots for reference. Please check and confirm

[SBS_CPQ_QUOTE_PKG_success_deploy.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6680872/SBS_CPQ_QUOTE_PKG_success_deploy.docx)

Thanks,
Somu

**Comment by TinaGriffin** [comment]
The SBS_CPQ_QUOTE_PKG deployment looks as expected now.  The only other thing I had to do was create the Grant to the CPQ_USER from the front end deployment.  STG looks good, can you make the same change in INT please.

**Comment by amitjori** [comment]
Hi Team,

Below is the latest update from Oracle.

Hi Amit,
Sorry for the delay in response .
I am currently working in an internal instance to try and figure this out .But no matter what I am doing the issue is not getting reproduced .

This is most likely caused by something in the environment .Would it be possible to refresh this environment and then try from the scratch ?
The reason why I am saying this is because we already manage to fix it in one environment and here in my internal instances is not getting reproduced .

Thanks,
Florin

**Comment by TinaGriffin** [comment]
I'm sure this has nothing to do with the issue, but I did notice that a comment was put into the package body....it appears from the retrofit as it is not there in 12.1.3.  It is actually confusing to have it there because it is not even for the same package name.  It should be removed.  You can compare it to 12.1.3 code and see it's not there.  I'm sure nothing to do with this issue but retrofitting should not have put this there for a totally unrelated package.

In SBS_CPQ_QUOTE_PKG compiled under APPS schema in the package body:
--  DDL for Package Body PBS_OKS_CONT_AUTHOR_REP_PKG
-- Name         Date (MM-DD-YYYY)       -- Description

**Comment by TinaGriffin** [comment]
In fact I looked through all the SOA packages and this was the only one that was retrofitted (according to the comments anyway).

**Comment by vinaytalasila** [comment]
Just an update...Currently this is not working in INT 12.2.10 and Pre-Prod instances. 

In INT 12.2.10 instance, DBA team and technical team has checked the patches, invalid objects, roles and retrofit objects by comparing with STG 12.2.10 and did not find any differences.

So in Pre-Prod instance, after DBA team deployed retrofit objects they deployed the **ASO_QUOTE_PUB** seeded package and **SBS_CPQ_QUOTE_PKG** custom package and it did not work. DBA team has also followed the below steps as per Oracle support representative and still facing the same issue. **DBA team is still working with Oracle support on this. When we receive any major updates from Oracle support then will update the status in this issue ticket.**

1.
a)Drop the ASO_QUOTE_PUB package package spec and body from the database
b)Drop the custom SBS_CPQ_QUOTE_PKG package package spec and body from the database

2.
a) Delete the ASO_QUOTE_PUB irep object using the "DeleteFromIRep.sql" that I have shared previously.
b) Delete the Custom irep object using the "DeleteFromIRep.sql" that I have shared previously.

3. Make sure that the packages does not exist in any other schema and that the irep object was removed.

4. Bounce the database and the application

5.Clear the cache using function administrator .

How To Clear The Cache Using Functional Administrator? ( Doc ID 759038.1 )

6.Reinstall the BOTH seeded and custom package spec and body from the WORKING instance

7.Make sure the packages are valid
The following query can be used to confirm that package exists and is valid
select object_name, object_type, status, owner
from dba_objects
where object_name in = ('ASO_QUOTE_PUB','SBS_CPQ_QUOTE_PKG');

8.
a)Upload the irep object from the asopqtes_pls.ildt ILDT using FNDLOAD
b)Upload the irep object from the custom ILDT using FNDLOAD

9.Deploy the services 

Thanks
Vinay Talasila

**Comment by lindamrigo** [comment]
This was the SR
SR 3-16480460771 : Unable to deploy Web Service

**Comment by lindamrigo** [comment]
This was the CSI number: 
<html><body>


  | 14443167
-- | --



</body>
</html>

**Comment by vinaytalasila** [comment]
Meeting minutes from our todays status meeting:
1) DBA team is still working with Oracle customer support. Amit will escalate the **SR-3-26108882831**. 
1a) Amit will reach out to Jack (Oracle Support - Technical Manager) if he can and get the insights of the deployment issues that he worked on during the year 2018.
2) In **Pre-Prod**, Amit will deploy the old SBS_CPQ_QUOTE_PKG (before retrofit). Deploy and see whether it works.
3) Tina will test the orders in **STAGE 12.2.10** and check whether the full functionality is working in that instance or not.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
3. Tina will test the orders in STAGE 12.2.10 and check whether the full functionality is working in that instance or not.
Response:  I took a CPQ Quote that had already been submitted successfully to EBS.  I resubmitted it again (that should create a new EBS quote and order).  I did this twice.  Customer 106147.  The EBS Quote created, Q # 198188 or Q # 198199.  The Orders created.  O # 939884 or O # 949885.  HOWEVER, the tmp and recap did not create, and it errored out.  So that tells me the TMP Recap SOA Web service may need undeployed and redeployed in STG.

**Comment by TinaGriffin** [comment]
This is the log message for the STG tmp recap

Message |   | Service execution error - Parse array conversion error. An error occurred while parsing XML representing a Java array. Unable to convert the XSD element P_SBS_TMPRECAP_TBL whose collection type is APP

**Comment by vinaytalasila** [comment]
Tina,

Thank you for your update. We will review the error and keep you posted. If needed we will have a Teams meeting with you today.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
I found this document.  Will anything in here help?  It tells you how to deploy an API in an upgrade:
"upgrade:-Will upgrade a service from 12.1.X to 12.2"

How To Perform Actions On API's From Backend in R12.2? (Doc ID 1664395.1)

**Comment by TinaGriffin** [comment]
Also found this troubleshooting guide:
Oracle E-Business Suite Integrated SOA Gateway Troubleshooting Guide, Release 12.2 (Doc ID 1317697.1)

**Comment by amitjori** [comment]
Hi Tina,

We have undeployed and deployed package "SBS_QOT_TMP_RECAP_PKG" in STG instance. Can you please re-test the CPQ connection now in STG instance?

Regards,
Amit

**Comment by TinaGriffin** [comment]
STG still had the same error: "<ISGServiceFault> <Code>ISG_SERVICE_EXECUTION_ERROR</Code> <Message>Error occurred while executing the web service request</Message> <Resolution>System error, please see service log trace for details.</Resolution> <ServiceDetails> <ServiceName>SBS_QOT_TMP_RECAP_PKG</ServiceName> <OperationName>TMP_SALES_RECAP_PRC</OperationName> <InstanceId>0</InstanceId> </ServiceDetails> </ISGServiceFault> "

**Comment by TinaGriffin** [comment]
I tried with another customer in STG and still getting this on the tmp recap (error that shows in CPQ).  So I think we should try to do the same fix on this SOA Web Service that was done to fix the Quote one in STG.
<ISGServiceFault> <Code>ISG_SERVICE_EXECUTION_ERROR</Code> <Message>Error occurred while executing the web service request</Message> <Resolution>System error, please see service log trace for details.</Resolution> <ServiceDetails> <ServiceName>SBS_QOT_TMP_RECAP_PKG</ServiceName> <OperationName>TMP_SALES_RECAP_PRC</OperationName> <InstanceId>0</InstanceId> </ServiceDetails> </ISGServiceFault>

**Comment by TinaGriffin** [comment]
I just found a difference in STG for the TMP Recap.  It's an old script I had to check the aliases of the SOA deployments....note in the below output the tmp / recap has a url of snaponbusinesssolutions where the others have snapbs.
Run the below to see the difference:

--Also, you can find the existing aliases from this table:
 select class_id,DERIVED_CLASS_ID,WSDL_URL, Service_alias, a.creation_date
from FND_SOA_SERVICES a
where service_alias like 'SBS%'

**Comment by TinaGriffin** [comment]
[FND_SOA_SERVICES table differences between instances.xlsx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6811624/FND_SOA_SERVICES.table.differences.between.instances.xlsx)

**Comment by TinaGriffin** [comment]
I've attached the differences I've found in the FND_SOA_SERVICES table between the 3 instances.  The ones in INT and STG that are green...the only difference is the :443.  The ones in red are differences altogether and should be addressed.  It looks like some cleanup needs done in that table as it should only reflect true SOA services that are used or have been tried in my opinion...just like what shows in 12.1.3 prod.

**Comment by vinaytalasila** [comment]
Tina,

Thank you for providing the details. Apart from the details that you provided, I tried to extract the details from Pre-Prod instance as well but I am unable to connect at this time. I will request Amit to look into the file that you provided and your comments. 

Today morning we have compared the custom packages related to SBS_CPQ_QUOTE_PKG. Extracted the logs between INT 12.2.10 and STAGE 12.2.10. We will review them as well. We noticed that 'Grant' is missing in INT12.2.10 instance. We will investigate regarding that as well. 

Oracle support has provided an additional step in today's comment. As those steps need an instance bounce, Amit will do that activity tonight.

**@amitjori** : Could you please review 'FND_SOA_SERVICES table differences between instances.xlsx' file, Tina's above comment and keep us posted.

Thanks 
Vinay

**Comment by TinaGriffin** [comment]
The Grant needs to be added after it's deployed.  The problem is it won't deploy.

**Comment by amitjori** [comment]
Hi Team,

We followed the consolidated action plan given by oracle but still no luck. Oracle Quoting is looking further below is the update from Oracle in Original SR 

Hi Praveen ,

The custom package has a dependency on the seeded ASO_QUOTE_PUB and this is the reason why is not getting successfully deployed .
The ERROR "Error reflecting element type for collection type PRICE_ATTRIBUTES_TBL_TYPE" actually comes from the ASO_QUOTE_PUB package .

PRICE_ATTRIBUTES_TBL_TYPE it is a Table TYPE coming from the ASO package.

Could you please review this package and the type associated with it from product point of view ?

Thanks,
Florin

**Comment by amitjori** [comment]
Hi Tina,
tmp / recap has a url of snaponbusinesssolutions where the others have snapbs. - This has been fixed in STG we undeployed the package and deployed it again.


![image](https://user-images.githubusercontent.com/85238919/125605588-50a18358-95c0-4362-9c16-efc59d4d4a55.png)

**Comment by TinaGriffin** [comment]
Still getting the same tmp recap error in STG.  I tried the CPQ Quote I was working with and also started a new quote from scratch and both still got the tmp error.

**Comment by amitjori** [comment]
Hello Tina,

We were able to successfully deploy the SBS_QOT_TMP_RECAP_PKG now , can you please test the cpq connection and confirm.
We tried to drop and recreate the SBS_QOT_TMP_RECAP_PKG today again this time we undeployed the package before dropping and re-creating the package and irep.
Regards,
Amit

**Comment by TinaGriffin** [comment]
Amit,
I've tried this several times.  I am not getting the same error, but I am now getting this one.  Which this one should be an easy one.  After you deployed you didn't create the grant for the CPQ_USER.  This step has to be done and this is the error that we're getting.  However, I went out to SOA and did the Grant and retried and we still get the same error.  If you go to SOA responsibility and go to the Administration Tab, you'll see the logs of each time I tried the tmp recap says Failure.

<ISGServiceFault> <Code>ISG_SERVICE_AUTH_FAILURE</Code> <Message>User is not authorized to execute the service</Message> <Resolution>Please check whether the user has the requisite grants.</Resolution> <ServiceDetails> <ServiceName>SBS_QOT_TMP_RECAP_PKG</ServiceName> <OperationName>TMP_SALES_RECAP_PRC</OperationName> <InstanceId>0</InstanceId> </ServiceDetails> </ISGServiceFault>

**Comment by TinaGriffin** [comment]
Oh wait a minute...that user grant error did get fixed.  Now it has  this error:

<ISGServiceFault> <Code>ISG_SERVICE_EXECUTION_ERROR</Code> <Message>Error occurred while executing the web service request</Message> <Resolution>System error, please see service log trace for details.</Resolution> <ServiceDetails> <ServiceName>SBS_QOT_TMP_RECAP_PKG</ServiceName> <OperationName>TMP_SALES_RECAP_PRC</OperationName> <InstanceId>0</InstanceId> </ServiceDetails> </ISGServiceFault>

**Comment by amitjori** [comment]
We had a OWC session with oracle today and they found that the package body version of ASO quote is on a lower version and suggested to apply a patch which did not helped to solve the issue Oracle is checking further on this with ASO development team.

Following osberved.

$Header: asopqteb.pls 120.11.12020000.19

$Header: asopqtes.pls 120.20.12020000.27 2020/03/13 17:52:03 akushwah ship $ */

Action plan
===============

1) Asked to apply the following patch 33005615:R12.ASO.C

Also checking with DEV via forums and updating collab SR on what exactly required from product team as the Issue working fine in Clone of Upgrade envt

**Comment by TinaGriffin** [comment]
In STG, for the tmp recap...it says to see the service log trace for details.  Do you know where that's at?  Also, isn't there something you have to do to copy the class id to both servers, internal and external?  I think I saw something like that in the emails I sent you last night.

**Comment by TinaGriffin** [comment]
This just keeps getting more confusing.  I just tried to do an order in CPQ INT....fully expecting it to not work since the custom Quote pkg isn't deployed yet in 12.2.10 INT.  It worked...so it created quote number 195356.  So I went out to EBS to look up that quote and it's really old.  So I ran the below in TOAD and found that it created the quote in INT 12.1.3 instead of 12.2.10.

select * from aso_quote_headers_all
where quote_number = '195356'

**Comment by TinaGriffin** [comment]
Nevermind...I figured out what I did.  So we had rows in the CPQ Site Variables table in there for the old urls when we were in OMCS and new rows I had added for OCI on the next page....I had accidentally changed the url on the old OMCS rows instead of the new rows we entered for OCI urls.  I'm updating the urls in the oci lines now.

**Comment by TinaGriffin** [comment]
Oh and one more thing...the lines in the table for OCI all used snaponbusinesssolutions in the url.

**Comment by TinaGriffin** [comment]
In STG Can we turn Audit on for the tmp recap web service under Soa responsibility/Administration/Configuration.  So we can maybe get a log message of what's really happening there.  I just don't understand why this web service, even though deployed is still erroring...unless it's looking for the class id on the external server which is what I'm thinking, the reason is because the WADL returns for the snapbs....but CPQ is using the url of snaponbusinesssolutions and that is where the error is returning for tmp/recap in STG.

**Comment by arsidhan** [comment]
SR is now 24X7. I will be watching it.
-Hanmant

**Comment by amitjori** [comment]
Hello Tina,

SBS_QOT_TMP_RECAP_PKG is now pointing to external can you please retest now and confirm?

**Comment by amitjori** [comment]
Hi Team,

We tried the action plan given by Jack (copying the artifacts from working to non working instance) but still facing the same issue.

Oracle has created a bug for this issue now.

Regards,
Amit

**Comment by amitjori** [comment]
Hello Tina,

We have re-deployed SBS_QOT_TMP_RECAP_PKG in STG instance on internal node, can you please re-test this one more time and confirm?

Regards,
Amit

**Comment by TinaGriffin** [comment]
For TMP Recap in STG.  when you had it deployed on external node, no error, although I couldn't open the tmp recap in EBS because the recap page won't open.  When deployed on internal node, I'm back to getting the same error.  You should be able to see in the Administration tab where it worked this morning and now is failing again.  We need to look at 12.1.3 SOA deployments and check the wsdls to see if they say snapbs or snaponbusinesssolutions.
<ISGServiceFault> <Code>ISG_SERVICE_EXECUTION_ERROR</Code> <Message>Error occurred while executing the web service request</Message> <Resolution>System error, please see service log trace for details.</Resolution> <ServiceDetails> <ServiceName>SBS_QOT_TMP_RECAP_PKG</ServiceName> <OperationName>TMP_SALES_RECAP_PRC</OperationName> <InstanceId>0</InstanceId> </ServiceDetails> </ISGServiceFault>

**Comment by TinaGriffin** [comment]
Can you get this page working in STG https://ebstest2.snapbs.com/OA_HTML/OA.jsp?page=/oracle/apps/pbs/quote/header/webui/XXSalesRecapPG&QuoteNumber=198206&AccountNumber=236220&QuoteName=MID%20STATE%20ISUZU%20TRUCK&ContactName=&CustomerName=MID%20STATE%20ISUZU%20TRUCK&OpptyName=&retainAM=Y&addBreadCrumb=Y&_ti=395124698&oapc=20&oas=xJ0_AMegpaYsztmO4gzqig..


Error Page
--
You have encountered an unexpected error. Please contact your System Administrator for assistance.

**Comment by lindamrigo** [comment]
in 12.2.10
# +======================================================================+
# |    Copyright (c) 2005, 2019 Oracle and/or its affiliates.           |
# |                         All rights reserved.                         |
# |                           Version 12.0.0                             |
# +======================================================================+
#
# $Header: isgagent_properties_FMW.tmp 120.1.12020000.4 2019/11/28 08:40:06 lmanda ship $
# ISG PROPERTIES FILE
#

ISG_SOA_EXTERNAL_URL=%s_soa_external_url%
ISG_SOA_INTERNAL_URL=%s_soa_internal_url%
ISG_SOA_ADMIN_SERVER_URL=%s_soa_admin_url%
ISG_SOA_ADMIN_USER=ASADMIN
ISG_SOA_ORACLE_HOME=%s_soa_oracle_home%
ISG_AGENT_JNDI_NAMES=TPQS2I
TPQS2I.ISG_RUNTIME_CONTEXT=AGENT
TPQS2I.ISG_TEMP_DIRECTORY_LOCATION=/tpqs2i/12.2/STG/fs_ne/inst/TPQS2I_ssbsashebsap3/soa/
TPQS2I.ISG_EBS_EXTERNAL_URL=https://ebstest2.snapbs.com:443
TPQS2I.ISG_EBS_INTERNAL_URL=https://ebstest2.snapbs.com:443
javax.xml.parsers.DocumentBuilderFactory=oracle.xml.jaxp.JXDocumentBuilderFactory
TPQS2I.ISG_EBS_ADMIN_SERVER_URL=http://ssbsashebsap3.oci.snapbs.com:7021

But the OCJ4.properties file also had these lines that are not there now
SOA_ENABLE_SESSION_CREATION=FALSE
SOA_ENABLE_STANDALONE_LOGGING=TRUE 

Just commenting on the differences

**Comment by amitjori** [comment]
Hi Team,

OWC with oracle has been scheduled tonight at 10:00 PM CST.

Regards,
Amit

**Comment by lindamrigo** [comment]
There are differences in file permissions between 12.1.3 production and 12.2.10 Stage.  I don't know if that makes a difference

[apppqs1i@sbsashpebsap1 REST]$ ls -ltr
total 148
-rw-r----- 1 apppqs1i dba 26423 May  6  2020 ISG_SBS_CP_GET_SN9143483.sql
-rw-r----- 1 apppqs1i dba   752 May  6  2020 ISG_SBS_CP_GET_SN9143483_drop.sql
-rw-r----- 1 apppqs1i dba 22242 May  6  2020 APPS_ISG_SBS_CP_GET_SN9143483_SBS_CPQ_SNAPSHOT_PKG-24GET_SNAP.xsd
-rw-r----- 1 apppqs1i dba 22242 May  6  2020 APPS_SBS_CPQ_SNAPSHOT_PKG_GET_SNAPSHOTINFO.xsd
-rw-r----- 1 apppqs1i dba 23197 May  6  2020 GET_SNAPSHOTINFO_SYNCH_TYPEDEF.xsd
-rw-r----- 1 apppqs1i dba  1481 May  6  2020 GET_SNAPSHOTINFO_apps.jca
-rw-r----- 1 apppqs1i dba  2006 May  6  2020 GET_SNAPSHOTINFO.wsdl
-rw-r----- 1 apppqs1i dba  1043 May  6  2020 SBS_CPQ_SNAPSHOT_PKG.wsdl
-rw-r----- 1 apppqs1i dba  1347 May  6  2020 SBS_CPQ_SNAPSHOT_PKG_rest.wadl
drwxr-x--- 2 apppqs1i dba  4096 May  6  2020 dist
-rw-r----- 1 apppqs1i dba  1323 May  6  2020 RESTHeader.xsd
-rw-r----- 1 apppqs1i dba  1427 May  6  2020 ISGServiceFault.xsd
-rw-r----- 1 apppqs1i dba 12328 May  6  2020 REST.zip

[aptpqs2i@ssbsashebsap3 REST]$ ls -ltr
total 56
-rw-r--r-- 1 aptpqs2i dba 26597 Jul 20 04:57 ISG_SBS_CP_GET_SN9143483.sql
-rw-r--r-- 1 aptpqs2i dba   752 Jul 20 04:57 ISG_SBS_CP_GET_SN9143483_drop.s
-rw-r--r-- 1 aptpqs2i dba  1136 Jul 20 04:57 GET_SNAPSHOTINFO_apps.jca
-rw-r--r-- 1 aptpqs2i dba  1578 Jul 20 04:57 GET_SNAPSHOTINFO.wsdl
-rw-r--r-- 1 aptpqs2i dba   720 Jul 20 04:57 SBS_CPQ_SNAPSHOT_PKG.wsdl
-rw-r--r-- 1 aptpqs2i dba  1365 Jul 20 04:57 SBS_CPQ_SNAPSHOT_PKG_rest.wadl
-rw-r--r-- 1 aptpqs2i dba  1450 Jul 20 04:57 SBS_CPQ_SNAPSHOT_PKG_rest_http.dl

**Comment by lindamrigo** [comment]
Where is the ServiceGenerator.log  located at?

**Comment by TinaGriffin** [comment]
Here is a MOS document that seems to have the same issue with the TBL data types as inputs.  This was from 12.2.6 and there was a patch and I've verified that patch is in 12.2.10 but maybe 12.2.10 has the problem still even after the patch.  Reminder that these TBL types are failing on multiple different with different table names SOA web services between INT and PRE-PROD.

EBS SOA Rest APIs Failed On Error While Executing Service (Doc ID 2451877.1)

**Comment by TinaGriffin** [comment]
This is a MOS doc for the other error we are hitting

Failed to deploy the REST webservice in 12.2.8 after CPU patch application (Doc ID 2580541.1)

**Comment by amitjori** [comment]
Hello Tina,

Even I got the same note id some time before while searching on MOS , I checked and the index mentioned in the doc id is valid in STG INT and PRE-PROD. Below is the screen print from PRE-PROD

![image](https://user-images.githubusercontent.com/85238919/126374297-287a18ea-c4c2-49ec-aaee-6f07edb83b0e.png)


Regards,
Amit

**Comment by amitjori** [comment]
Hi Team,

We had a OWC session with Oracle today where Sai(from Oracle Quoting) and Abhinav(from Development) joined the called .

We explained them the issues that we are seeing in different environments on screen sharing session and compared the logs between working and non working environment, as requested we uploaded the logs and Apps Check Diagnostics output from working and non working environment to the SR. As of now no direct outcome from this OWC session and development team is checking this issue internally. Escalation status has been changed to Escalated now.

Awaiting further update from Oracle.

Regards,
Amit

**Comment by ashoksnapfj** [comment]
Hi Tina,

REF:: 

Can you get this page working in STG https://ebstest2.snapbs.com/OA_HTML/OA.jsp?page=/oracle/apps/pbs/quote/header/webui/XXSalesRecapPG&QuoteNumber=198206&AccountNumber=236220&QuoteName=MID%20STATE%20ISUZU%20TRUCK&ContactName=&CustomerName=MID%20STATE%20ISUZU%20TRUCK&OpptyName=&retainAM=Y&addBreadCrumb=Y&_ti=395124698&oapc=20&oas=xJ0_AMegpaYsztmO4gzqig..

Error Page

You have encountered an unexpected error. Please contact your System Administrator for assistance.

**we are able to fetch quote#198207 from Pre-Prod but having issue in STG instance. we are working on this issue in STG.

![image](https://user-images.githubusercontent.com/84917490/126644887-3b23e715-b5f5-42a4-823d-4dbc96e24b99.png)


Thanks
Ashok.T**

**Comment by vinaytalasila** [comment]
Just a status update regarding the testing in STAGE 12.2.10 instance today: 
1) Tina, DBA team and I had a web meeting and tested two cases successfully. 
a) Using the existing quote # 198207, resubmitted it in CPQ and it has created a new quote # 198208 - CPQ-1341 - Sales Order # 939904.
b) Created a new quote # 198209 - CPQ-1539 - Sales Order # 939905.
2) Above test cases did not work on 7/19/2021.
3) As the above two test cases worked, Test-Cycle-2 can be done now in that instance.
4) The only issue that was faced is during 'Sales Recap'. Need to investigate this and fix.
5) Possible actions that are done between 7/19/2021 and 7/22/2021 in STAGE 12.2.10 instance are a) Ran 'Gather Schema Statistics' and cleared cache.
6) Tonight, DBA team will do the same actions in INT 12.2.10 instance. Deploy the SBS_QUOTE% package in that instance and retest.
7) Tomorrow, another round of testing will be done in STAGE 12.2.10 to make sure that everything works as today.
8) Review Tina's email that was sent today afternoon. 

Thanks
Vinay

**Comment by vinaytalasila** [comment]
In STAGE instance, 'ICX: Numeric characters' profile option value at the site level was 10,000,00 

Today we corrected that value to 10,000.00 and retested the 'Sales Recap' and it worked. 

Tina,

Could you please logout of your current STAGE instance session and retest 'Sales Recap' function now in the STAGE instance and let us know the results.

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment]
I have verified the Recap and TMP pages are opening perfectly and the data is there in STG for new orders we just entered yesterday.

**Comment by vinaytalasila** [comment]
Thank you for your update Tina.

**Comment by TinaGriffin** [comment]
I've tested CPQ again today in STG.  
I’ve resubmitted CPQ-1341.  It created new quote 198211  and order 939907.
I created new quote CPQ-1540.  It created new quote 198212 and order 939908.

No errors, and the data all flowed correctly to EBS and TMP/Recap pages all opened correctly.

**Comment by vinaytalasila** [comment]
Thank you for your update Tina.

**Comment by vinaytalasila** [comment]
Just an update...I have requested for a OWC session with Oracle support on 7/26/2021 any time between 9:00 AM CST to 12:00 Noon CST and include Product, SOA and DBA groups. Oracle support has responded to my request mentioned below.
"Due to the differences in time zones between the groups, we may not be able to confirm a time today. We will continue to monitor both groups and let you know as soon we have the next actions"

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Tina/Team,

OWC session was conducted with Oracle today at 2:00 PM IST where only Anwar from ORDS team joined the call to check the issue from ORDS side, he mentioned that this does not look to be an ORDS side issue after checking the SOA issue on screen sharing.

He said he is not sure how SOA Rest services are using ORDS to deploy Seeded SOA Oracle packages and will be updating the parent SR(SR 3-26108882831 : SOA REST service deploy failed).

I did update the parent SR requesting to join the same call with ORDS team so we can troubleshoot the issue , but there was no response.

Current Status of parent SR is - @DEV - Development Working

Regards,
Amit

**Comment by amitjori** [comment]
Hello Tina/Team,

We had OWC session today(08/02/2021) at 2:00 PM IST. Below members from respective teams joined the call but Abhinav from ASO development team was unable to join the call due to some technical issues. Florin has checked the issue one more time from SOA side and is not able to figure out the root cause and suggested to check the issue further with development team, Sai said he will re-schedule the call one more time after following up with Abhinav from development team.
Florin - from SOA Team
Sai - from Oracle Quoting Team
Mohammed - from ORDS Team

Regards,
Amit

**Comment by amitjori** [comment]
Hi Tina/Team,

We had a OWC session with Oracle today(08/05/2021) 

Below is the synopsis of OWC session

We questioned Abhivan/Sai about the error message that we see in the log file from front end , they said as of now they are unable to debug the error and this error message could be misleading and they do not see any issue in the code, per them packages are present and valid, table type seen in the error log is also present in packages and they are suspecting an issue from SOA side based on the error "Error in the generating PLSQL package" and SOA team should check this.

Florin from SOA team has suggested ASO team to open a collaborative bug with SOA development team as he is not sure what exactly the wrapper(ISG_ASO_QUOTE_PUB_CREATE_QUOTE) is trying to check in ASO_QUOTE_PUB package.

Sai has opened a collaborative bug with SOA development team and will scheduled another OWC session as soon as he has update from SOA development

Below members from respective teams joined the call.
Florin - from SOA Team
Sai - from Oracle Quoting Team
Abhinav - from ASO development Team
Fujitsu Team - Amit, Soma, Ashok and Akshay

**Comment by vinaytalasila** [comment]
- Today morning Sai, Amit and I talked to Deepak and his associate and complained that Oracle is not providing us any update daily and no progress on the issue.

- After OWC session was concluded on 08/05/2021 at around 1:15 PM **IST**, The following defect was entered with the SOA team -

Bug 33193269 - SOA REST SERVICE DEPLOY FAILED

The Development teams are reviewing the code and related logging calls for the ISG package processing.

-Latest update from Deepak (Oracle Support) is **the bug has been escalated to the highest level in the Development team.  It is getting the correct attention**

Thanks
Vinay

**Comment by amitjori** [comment]
Hi Tina/Team,

We had a OWC session today with Oracle SOA development team where Sai Munnaluri joined the call from SOA development team.

He enabled the debug and is in process of  creating a standalone java script to analyse the issue with "Exception while executing JPublisher wrapped" error.

He is suspecting an issue with JPulisher and will update the SR in 1 hour or will schedule one more OWC today to work further on this issue based on his findings.

Below members from respective teams joined the call.
Florin - From SOA Team
Sai  Munnaluri - From SOA Development team
Sai - From Oracle Quoting Team
Fujitsu Team - Amit, Soma, Ashok and Akshay

Regards,
Amit

**Comment by vinaytalasila** [comment]
Tina,

From today, SOA development team member (Sai) also joined the status call with Oracle support. We got direct updates from him today in the call. He mentioned that he will review the log files that are attached by Amit and he believes that there is something with Jpublisher. 

He has requested us to provide the documents that we used to configure SOA REST services after 12.1.3 to 12.2.10 upgrade. Amit has provided the details to him. He will review that as well and provide actions steps tonight.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update....Amit tried to compile the ASO invalids but they are erroring out. Updated this in the SR and they provided new action plan to compile these objects even this action plan did not help. Got an approval from Tina to restore INT 12.2.10 with 08/02/2021 backup. DBA team will do that and if we see many 'Invalids' then we will run appscheck report and provide ASO_QUOTE_PUB package details to Oracle support and we will followup with development for the next actions.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update...We had a call with Oracle support team today morning and it was assigned to a support engineer in US during the morning hours. That person is going to work on this issue and request us information / meetings if needed. They have scheduled daily meetings with us till 08/27/2021. I will keep you posted when I get any major updates from them.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Just an update.....

![image](https://user-images.githubusercontent.com/84878630/130479217-2e4b7f80-396c-4260-b2ef-d561dcece53a.png)

Below note was fwd by Tina when she got an error (shown above) while testing TMP/RECAP on Friday (8/20/2021). Amit has performed the steps over the weekend and it works now in INT 12.2.10 and STG 12.2.10 instances.

SOA Gateway API - FND_SOA_SERVICE_EXECUTION_ERR java.sql.SQLException: ORA-04063: package body has errors ORA-06508: PL/SQL: could not find program unit being called (**Doc ID 2011602.1**)

Cause
The modified package was not synchronized across the instance, specifically the new code is out of synch with the pre existing jar files.  
 
Although the package was recompiled, the jar files were not regenerated.  
Because the error message had a java element the jar files should be regenerated in addition to recompiling the package, eg:

"An error occurred while preparing and executing the ISG_XXX_WS$GET_EBS_ORD API. Cause: java.sql.SQLException: ORA-04063: package body ""APPS.ISG_GNDL"" has errors
ORA-06508: PL/SQL: could not find program unit being called: ""APPS.ISG_GNDL""
 
Solution
1. Use adadmn utility to force regnerate the product jar files. 
2. Recompile the package (again if necessary)
3. Restart all middle tier services
4. Regenerate the web service.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
Amit,

When you have time, could you please mention the steps in this ticket that are provided by Oracle support to fix this issue.

Thanks
Vinay

**Comment by vinaytalasila** [comment]
From: Griffin, Tina <Tina.Griffin@snapon.com> 
Sent: Monday, August 23, 2021 10:06 AM
To: Jori, Amit <Amit.Jori@fujitsu.com>; Talasila, Vinay <Vinay.Talasila@fujitsu.com>; Arsid, Hanmant <Hanmant.Arsid@fujitsu.com>; Muthunarayanan, Somasundaram <Somasundaram.Muthunarayanan@fujitsu.com>
Subject: RE: INT TEST

In INT, the Snapshot is not loading in CPQ.  
 I noticed the other day that the snapshot in INT was loaded on the external.
![image](https://user-images.githubusercontent.com/84878630/130526309-5d106459-2ef0-4d15-b08a-bf938b2742f8.png)
 

The WADL returns:
<ISGServiceFault>
<Code>ISG_SERVICE_EXECUTION_ERROR</Code>
<Message>
Error occurred while executing the web service request
</Message>
<Resolution>
System error, please see service log trace for details.
</Resolution>
<ServiceDetails>
<ServiceName>SBS_CPQ_SNAPSHOT_PKG</ServiceName>
<OperationName/>
<InstanceId>0</InstanceId>
</ServiceDetails>
</ISGServiceFault>

**Comment by amitjori** [comment]
Hello Tina,

Could you please re-test SBS_CPQ_SNAPSHOT_PKG in INT 12.2.10 and confirm the results?

Regards,
Amit

**Comment by TinaGriffin** [comment]
The Snapshot is working in INT now.  Thank you.

**Comment by vinaytalasila** [comment]
Tina, Please find the attached document that was prepared by Amit. 
[SOA Issue fix during 12.2 upgrade.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/7087066/SOA.Issue.fix.during.12.2.upgrade.docx)

If that looks good then could you please 'Close' this issue.

Thanks
Vinay

**Comment by TinaGriffin** [comment]
The document looks good for the "SOA Issue fix during 12.2. upgrade.docx".

**Comment by TinaGriffin** [comment]
The document looks good for the "SOA Issue fix during 12.2. upgrade.docx".
