### ISSUE TITLE
INT Labels PBS Label Batch Generation Throwing Error

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#73]
PBS Label Batch Generation Throwing Error
Error Message: ORA-00942: table or view does not exist

Responsibility SBS Labels Administrator >
Run Concurrent Batch Set >PBS Create Label Batch Set
Enter Parameters > OEM > CY
Product 1 > KIA NA EPC5 USB
Product 2 > KIA NA EPC5 USB
One Time Only Replicator > Richfield
Batch Version > 2021-07
Batch Date> 01-JUL-2021
Business Unit > Auto

**Comment by lindamrigo** [comment]
[Labels Error.xls](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6718266/Labels.Error.xls)

**Comment by lindamrigo** [comment]
Product KIA NA EPC5 USB is now working but NISSAN EPC5 USB is not now. Friday both were not working. Still same error

**Comment by lindamrigo** [comment]
Missed package from production 
SBS_Label_Updates
![Prod SBS Label Updates](https://user-images.githubusercontent.com/85238444/123637638-3f594200-d7ec-11eb-95f4-084d5d9e9c81.JPG)
![DPQS2I SBS Label Update PKG](https://user-images.githubusercontent.com/85238444/123637643-41230580-d7ec-11eb-8fdc-0488c25a47af.JPG)

**Comment by ashoksnapfj** [comment]
Hi Linda,

SBS_Label_Updates is there, but error is in package "PBS_LABEL_BATCH_GEN_PKG" and this is fixed in both the instances.
Please test now and let us know.

Thanks
Ashok.T

**Comment by ashoksnapfj** [comment]
[73_PBS_Create_Label_Batch_Set.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6726339/73_PBS_Create_Label_Batch_Set.docx)

**Comment by lindamrigo** [comment]
Can you copy the package from Prod to both INT and Stage?

**Comment by ashoksnapfj** [comment]
Hi Linda,

No I changed in the package "PBS_LABEL_BATCH_GEN_PKG" by considering the stg/int  instances only,as this is already retrofitted. Means took from PROD only last time.

Now issue is fixed. Please test and let us know.

Thanks
Ashok.T

**Comment by lindamrigo** [comment]
The package is missing in 12.2.10.  It needs to be there.  Is there a problem with copying it over?

**Comment by ashoksnapfj** [comment]
Hi Linda,

While retrofit the package, there is some issue which is fixed now.

Thanks
Ashok.T

**Comment by lindamrigo** [comment]
There is still a problem.  There is  missing package. The package needs to be there. The problem is NOT FIXED until all configurations run without error.  Please copy the package from 12.1.3 Production to all 12.2.10 instances.  See attached error log and screenshot
[INT Label Error.xls](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6726546/INT.Label.Error.xls)
[DPQS2I SBS Label Error.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6726548/DPQS2I.SBS.Label.Error.txt)

**Comment by lindamrigo** [comment]
![INT Label Error 6 28 21](https://user-images.githubusercontent.com/85238444/123643260-33707e80-d7f2-11eb-9266-f98ccc27d1b8.JPG)

**Comment by lindamrigo** [comment]
![INT Missing Package](https://user-images.githubusercontent.com/85238444/123643561-81858200-d7f2-11eb-93b3-770593f76746.JPG)

**Comment by ashoksnapfj** [comment]
Hi Linda,

INT is down and it is up now, just now I remigrated package "PBS_LABEL_BATCH_GEN_PKG".
Please re test now let me know.

Thanks
Ashok.T

**Comment by lindamrigo** [comment]
Still erroring
![INT Invalid label package](https://user-images.githubusercontent.com/85238444/123650311-77668200-d7f8-11eb-87a0-8c44e032c433.JPG)
![INT Label Error 6 28 2021 10 04 AM EDT](https://user-images.githubusercontent.com/85238444/123650330-7afa0900-d7f8-11eb-94bb-b1ec2196379e.JPG)
![INT Missing Package](https://user-images.githubusercontent.com/85238444/123650335-7c2b3600-d7f8-11eb-8dac-a225ccc2b3ef.JPG)

**Comment by lindamrigo** [comment]
The package is invalid, SBS_LABEL_UPDATES package needs copied from production. It should have been dpqs2i but due to timing it was missed. 
![Prod SBS Label Package](https://user-images.githubusercontent.com/85238444/123650910-0b384e00-d7f9-11eb-84e4-e75e93630660.JPG)

**Comment by lindamrigo** [comment]
Error details log
[Report_Set_280621.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6726893/Report_Set_280621.txt)

**Comment by ashoksnapfj** [comment]
Hi Linda,

I ran the request set (PBS Create Label Batch Set) with same parameters as per above screen shot. And all the programs has been completed successfully in the INT instance.
Please find the attached document with screen shots for submitted program and database object also.

could you please re-connect your database and also application then submit new program (please don't use copy ) and let us know still if you face the issue, then we will setup call and work accordingly
[73_PBS_Create_Label_Batch_Set_v1.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6727104/73_PBS_Create_Label_Batch_Set_v1.docx)
.

Thanks
Ashok.T

**Comment by lindamrigo** [comment]
The package is still invalid. This will not be closed until the package is valid as it is in production.
![INT Invalid after compilation](https://user-images.githubusercontent.com/85238444/123657173-910ac800-d7fe-11eb-9293-78e28262dc0c.JPG)

**Comment by lindamrigo** [comment]
Also, why isn't the missing package in the INT instance? The date of the data says 4/18/2021 but the package was installed in production on 1/19/2021
![Production SBS Label Updates](https://user-images.githubusercontent.com/85238444/123657646-f9f24000-d7fe-11eb-8610-b36ed0154d26.JPG)

**Comment by Haqueraz** [comment]
Thank you for joining the meeting request. 
We are checking the DB objects and all looks good.
It looks like there is some issue in Toad.it is not getting the latest objects.

![image](https://user-images.githubusercontent.com/84917836/123663894-72a3cd00-d7fc-11eb-8bb6-6e6471a2ecfa.png)

**Comment by lindamrigo** [comment]
Resync'd Toad. now seeing package
